### ISSUE TITLE
Definir licenciamiento del proyecto

### ISSUE THREAD

**Issue by melalonso** [LabExperimental-SIUA/LibreScan#108]
Establecer licencia de Software Libre para LibreScan.

**Comment by Sufrostico** [comment]
Cómo recomendación se puede iniciar con una lista de las licencias de las bibliotecas que están siendo utilizadas. 

Y apuntar a GPL 3 o AGPL 3

**Comment by jamescr** [comment]
GPL3

+1

On Sun, Feb 14, 2016 at 10:49 AM, Aurelio Sanabria <notifications@github.com
