### ISSUE TITLE
Error en instalacion del LibreScan

### ISSUE THREAD

**Issue by Juliorc** [LabExperimental-SIUA/LibreScan#116]
Estuve instalando los paquetes del proyecto, pero el paquete "libturbojpeg0-dev" parece tener un problema por que dice que no existe.

**Comment by Juliorc** [comment]
tambien probe usar  "libturbojpeg1-dev" pero da el mismo error

**Comment by diugalde** [comment]
¿Cuál sistema operativo está utilizando? La guía fue hecha con Debian 8 Jessie.

**Comment by jyock97** [comment]
Estoy utilizando Ubuntu 14.04; el paquete "libturbojpeg0-dev" resulta no existir,  el único paquete parecido existente se llama "libturbojpeg"

**Comment by Sufrostico** [comment]
https://help.ubuntu.com/community/Repositories/Ubuntu#CD-ROM.2FDVD

Favor traten de agregar los repositorios de tipo "sources" (de código fuente) cómo el que aparece en la foto del link de arriba

**Comment by 5up3rD4n1** [comment]
Nos avisan si se solucionó el error para cerrar el issue.

**Comment by Juliorc** [comment]
por mi parte el problema esta resuelto, el paquete para ubuntu se llama "libjpeg-turbo8-dev"

**Comment by melalonso** [comment]
:+1:
