### ISSUE TITLE
Primer release

### ISSUE THREAD

**Issue by Sufrostico** [LabExperimental-SIUA/LibreScan#121]
Hola, 

Nos estamos atrasando mucho con este _release_ y perdemos la oportunidad de que Lupa y Enrique nos colaboren con pruebas y retroalimentación

Darle prioridad a esto.

Saludos

**Comment by diugalde** [comment]
La versión 0.1.2 ya podría ser utilizada, solo hay que solucionar que se pueda ejecutar desde terminal la aplicación, independientemente de un IDE.

**Comment by Sufrostico** [comment]
esa parte urge

**Comment by 5up3rD4n1** [comment]
Listo

https://github.com/LabExperimental-SIUA/LibreScan/releases/tag/V0.1.3

Ya se puede compartir la guia y con el release el programa se puede ejecutar desde 
        
        $ python3.4 main.py web
