### ISSUE TITLE
Archivos binarios .mo

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/LibreScan#135]
Al ejecutar la aplicación como lo indica el readme ocurre una excepción relacionada con los archivos de traducción de hileras:

~~~
    translations = translation(domain='messages', localedir='./web/i18n/locale', languages=[self.default_language])
  File "/usr/lib/python3.5/gettext.py", line 432, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'messages'
~~~

Al parecer faltan o no se están generando de forma automática los archivos binarios .mo

**Comment by diugalde** [comment]
@Sufrostico recuerdo que usted había mencionado algo respecto a esto. Se están compilando esos archivos durante la instalación del paquete de debian?

**Comment by Sufrostico** [comment]
Si, esta al final del.script postinst de debian, pero si se quiere instalar a pata no esta en ningun lado

**Comment by diugalde** [comment]
Ok, creo que en ese caso sería mejor dejarlo en el setup.py
