### ISSUE TITLE
Ejecutar libreScan modo "desarrollo"

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/LibreScan#137]
Creo que es importante contar con alguna forma de poder trabajar con LibreScan aunque no se tengan las cámaras conectadas. Si bien es claro que las cámaras son parte fundamental también es cierto que "cortan" un poco el ánimo de potenciales desarrolladores que quieran ayudar. 

Inicialmente se me ocurre en alguna forma de simular los datos que ofrecen las cámaras pero me gustaría saber si tienen alguna sugerencia.

**Comment by 5up3rD4n1** [comment]
¿Tener algunas imagenes precargadas para pruebas?

**Comment by Sufrostico** [comment]
Si, algo como un proyecto default para trabajar etapas posteriores a la toma de fotos sin la necesidad de las cámaras.

**Comment by jamescr** [comment]
Exacto. Quizás contar con imágenes precargadas puede ayudar a trabar en el flujo de generación del pdf propiamente dicho. Inclusive podríamos identificar imágenes difíciles (ej: tablas, fotos, con colores) para hacer issues específicos con ese tipo de imágenes.

Esa solución suena bien, pero no estoy si será lo único a tomar en cuenta una ejecución "modo desarrollo". Pensemos en los siguientes issues: #133 #131 #119 #94 #55, ¿bastaría con tener imágenes precargadas para entrarles?

**Comment by diugalde** [comment]
Listo #140
