### ISSUE TITLE
La imagen pesa menos después de ser rotada

### ISSUE THREAD

**Issue by diugalde** [LabExperimental-SIUA/LibreScan#54]
Estamos utilizando la biblioteca Pillow de Python para hacer la rotación de las imágenes y funciona bien, sin embargo pasan de pesar 3 MB a 1-2MB, esto puede afectar la calidad y por ende el resultado final después de ser procesada por scantailor. Hay que buscar alternativas.

**Comment by 5up3rD4n1** [comment]
Solved with JPEGTran
