### ISSUE TITLE
Pensar un nuevo nombre para el proyecto.

### ISSUE THREAD

**Issue by 5up3rD4n1** [LabExperimental-SIUA/LibreScan#6]
El proyecto necesita un nuevo nombre, sabemos que no es facil pensar un buen nombre para el proyecto por el contexto que se desenvuelve y las funciones que realiza, pero claramente maescan no es un buen nombre.

**Comment by Sufrostico** [comment]
Justificar pq el nombre no es apropiado.

**Comment by 5up3rD4n1** [comment]
A mi parecer el termino mae es utilizado en otros paices no es algo que identifique totalmente a Costa Rica (la idea del mae surgio porque queriamos algo tico en el nombre) tambien se utiliza en honduras y creo otros lugares. Otro de los motivos  es que suena a "My Scann" (no se si sea algo bueno o malo) y habiamos hecho el comentario que queriamos cambiar el nombre. Hay que proponer mas opciones.

**Comment by diugalde** [comment]
Nombre definido: Librescan
