### ISSUE TITLE
Empaquetamiento de LibreScan

### ISSUE THREAD

**Issue by 5up3rD4n1** [LabExperimental-SIUA/LibreScan#60]
Después de cumplir las metas con del primer release, debemos buscar alguien que nos oriente con el proceso de empaquetamiento e instalación en Python.

**Comment by jamescr** [comment]
Creo que esto ya @Sufrostico lo tiene listo. Lo etiqueto acá para que nos cuente.

**Comment by 5up3rD4n1** [comment]
Hay alguna documentación para esto? Sería muy chiva aprender!

**Comment by Sufrostico** [comment]
mmm, bajé este y el chdkptp de ser versión 1.0 en lugar de 3.0 (quilt) por ser más fácil de crear (sin embargo es más complicado si se tiene que empaquetar para múltiples arquitecturas), pero más fácil para introducir a otros estudiantes al empaquetamiento.

Además construí un repositorio utilizando reprepo (una utilidad super básica que permite crear su propio repo debian).

Saludos,
Aurelio

**Comment by jamescr** [comment]
Estaría bueno tomar un café/birita y escuchar los detalles de la solución. :smiley: 

Parece entonces este issue ya debería ser cerrado.
