### ISSUE TITLE
Actualizar guía de instalación de LibreScan

### ISSUE THREAD

**Issue by melalonso** [LabExperimental-SIUA/LibreScan#97]
Agregar la instalación de la dependencia JPEGTran usada para hacer transformaciones a imágenes JPEG.

**Comment by melalonso** [comment]
También hace falta agregar el comando para instalar  pexpect (pip3 install pexpect).

**Comment by 5up3rD4n1** [comment]
Comentar en algún lado que es necesario utilizar la versión full del CHDKPTP para las cámaras.

**Comment by diugalde** [comment]
La cámara debe estar en 'auto' para que sirva el enfoque.

**Comment by melalonso** [comment]
Ya están las lineas para instalar JPEGTran y pexpect. Faltaría especificar las otras 2 cosas.
